AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Production-ready secure S3 bucket:
  - HTTPS-only access
  - Deny unencrypted uploads
  - Access logging
  - Server-side encryption (SSE-S3)
  - Versioning
  - Ownership controls
  - Fully private (Block Public Access enforced)

Parameters:
  SecureBucketName:
    Type: String
    Description: Unique S3 bucket name for secure bucket
    Default: "secure-bucket-karim-2025-12-17"

  LogBucketName:
    Type: String
    Description: Unique S3 bucket name for access logs
    Default: "secure-bucket-logs-karim-2025-12-17"

Resources:

  # Log bucket for access logging
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LogBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      Tags:
        - Key: Name
          Value: s3-logs
        - Key: ManagedBy
          Value: CloudFormation

  # Main secure S3 bucket
  SecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SecureBucketName
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: access-logs/
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: s3-secure
        - Key: ManagedBy
          Value: CloudFormation

  # Bucket policy: HTTPS-only + deny unencrypted uploads
  SecureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SecureBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Deny all HTTP traffic
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${SecureBucket.Arn}"
              - !Sub "${SecureBucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: false

          # Deny unencrypted object uploads
          - Sid: DenyUnencryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub "${SecureBucket.Arn}/*"
            Condition:
              StringNotEquals:
                "s3:x-amz-server-side-encryption": "AES256"

Outputs:
  SecureBucketName:
    Description: Name of the secure S3 bucket
    Value: !Ref SecureBucket

  LogBucketName:
    Description: Name of the S3 bucket storing access logs
    Value: !Ref LogBucket
